export const dummyData = [
    {
      id: "1",
      jobTitle: "Software Engineer",
      industry: "Information Technology",
      companyName: "Tech Innovators",
      maxExperience: "6",
      minExperience: "3",
      location: "San Francisco",
      remoteType: "Remote",
      maxSalary: "80000",
      minSalary: "40000",
      totalEmployee: "50",
      applyType: "Quick apply",
    },
    {
      id: "2",
      jobTitle: "Data Scientist",
      industry: "Data Analytics",
      companyName: "Data Insights",
      maxExperience: "5",
      minExperience: "2",
      location: "New York City",
      remoteType: "Hybrid",
      maxSalary: "75000",
      minSalary: "35000",
      totalEmployee: "30",
      applyType: "Quick apply",
    },
    {
      id: "3",
      jobTitle: "Product Manager",
      industry: "Product Management",
      companyName: "Product Masters",
      maxExperience: "7",
      minExperience: "4",
      location: "Seattle",
      remoteType: "In-office",
      maxSalary: "90000",
      minSalary: "45000",
      totalEmployee: "40",
      applyType: "External apply",
    },
    {
      id: "4",
      jobTitle: "Graphic Designer",
      industry: "Design",
      companyName: "Creative Designs",
      maxExperience: "3",
      minExperience: "1",
      location: "Los Angeles",
      remoteType: "Remote",
      maxSalary: "60000",
      minSalary: "30000",
      totalEmployee: "25",
      applyType: "Quick apply",
    },
  ];
    

  export const emptyJobObject = {
    id: "", 
    jobTitle: "",
    industry: "",
    companyName: "",
    maxExperience: "",
    minExperience: "",
    location: "",
    remoteType: "",
    maxSalary: "",
    minSalary: "",
    totalEmployee: "",
    applyType: "",
  };

  export const applyNowStr = "Apply Now";
  export const externalApplyStr = "External Apply"

